Recreates the @when decorator for a new age.
Cronenbrogues/whimsylib pull request #4
Opened 2021-02-04 04:21 UTC by flosincapite

2021-02-04 04:24 UTC, flosincapite commented
I still need to write unit tests for both of the files touched here.

Test plan:
- update requirements in `cronenbroguelike` to point here;
- use `@whimsylib.when.when` (we should do some `__init__` magic to make that nicer) in place of `@adventurelib.when`;
- see how it plays out.

2021-02-04 20:36 UTC, xmunoz commented
This needs to be merged first: https://github.com/Cronenbrogues/cronenbroguelike/pull/122

2021-02-05 14:35 UTC, flosincapite commented
This still has some problems; I am working on it.

2021-02-05 20:15 UTC, xmunoz commented
> This still has some problems; I am working on it.

Ok, I'll wait until this is merged before trying to remove adventurelib references from cronenbroguelike.

2021-02-10 04:28 UTC, flosincapite commented
@abjose IT DOES THIS WHENEVER IT'S TOLD

2021-02-10 04:32 UTC, xmunoz requested changes

2021-02-10 04:32 UTC, xmunoz commented on whimsylib/when.py
> +    print(f'I don\'t understand "{command}."')
Blasphemer!

2021-02-10 04:52 UTC, xmunoz approved these changes
It's lit

2021-02-10 04:54 UTC, merged